@api = http://localhost:5000/api/tasks

###
POST {{api}}
Content-Type: application/json

{
    "title": "Task one",
    "description": "Description one"
}
###
GET {{api}}
###
GET {{api}}/625ca0f4f8df22d8ad1661d4
###
DELETE {{api}}/625cac9fc42f27d5efe935e4
###
PUT {{api}}/625ca114f8df22d8ad1661da
Content-Type: application/json

{
    "title": "Task One",
    "description": "Description One"
}