@api = http://localhost:4000/api/tasks

###
POST {{api}}
Content-Type: application/json

{
    "title": "Task Two",
    "description": "Description two"
}
###
GET {{api}}
###
GET {{api}}/625c95e93e880ff1288fe1f8
###
DELETE {{api}}/625c95e93e880ff1288fe1f8